import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { Dropdown } from 'flowbite-react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="root">
        <div className="navbar p-2">
          <div className="md:block sm:hidden ssm:hidden big-navbar">
            <div className="flex justify-between">
              <div className="left-bar flex">
                <div className="logo drop-shadow-md">Logo</div>
                <div className="ml-5 drop-shadow-md">Blog</div>
                <div className="ml-5 drop-shadow-md">Project</div>
                <div className="ml-5 drop-shadow-md">Career Path</div>
                <div className="ml-5 drop-shadow-md">About</div>
              </div>
              <div className="right-bar flex flex-end">
                <Image src={'/icon/sun.png'} height={24} width={24} />
                <div className="ml-10">VN</div>
              </div>
            </div>
          </div>
          <div className="sm:block md:hidden smal-navbar">
            <div className="flex justify-between">
              <Image src={'/icon/view-list.png'} height={36} width={36} />
              <div className="right-bar flex flex-end">
                <Image src={'/icon/sun.png'} height={24} width={24} />
                <div className="ml-10">VN</div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <div>
        <Dropdown label="Dropdown button">
          <Dropdown.Item>Dashboard</Dropdown.Item>
          <Dropdown.Item>Settings</Dropdown.Item>
          <Dropdown.Item>Earnings</Dropdown.Item>
          <Dropdown.Item>Sign out</Dropdown.Item>
        </Dropdown>
      </div>
    </>
  );
}
